#Assingnment-2
#Submitted TO:Afroja Ahmed Smrity(lacturer)
##Department of CSE[UITS]
Name: Mehedi Hasan Soykot
#Id: 0432320005101190


In [4]:

#Create personal matrix
import numpy as np

d1 = 0
d2 = 9

matrix = np.array([[d1, d2], [d2, d1+1]])

print("StudentID: 0432320005101190")
print("Personal Matrix:")
print(matrix)


StudentID: 0432320005101190
Personal Matrix:
[[0 9]
 [9 1]]


#Analyze Matrix


In [18]:
shape_A = matrix.shape
print("shape is:",shape_A)

det_A = np.linalg.det(matrix)
print("Determinant is :",det_A)

rank_A = np.linalg.matrix_rank(matrix)
print("Rank is :",rank_A)

eigenvalu  = np.linalg.eigvals(matrix)
print("Eigenvalues are :",eigenvalu)

#Inverse matrix
if det_A != 0:
  inv_A = np.linalg.inv(matrix)
  print("inverse matrix is:\n", inv_A)
else:
  print("Inverse dose't exist")



shape is: (2, 2)
Determinant is : -81.00000000000003
Rank is : 2
Eigenvalues are : [-8.51387819  9.51387819]
inverse matrix is:
 [[-0.01234568  0.11111111]
 [ 0.11111111  0.        ]]


#Value Change Expriment

In [13]:
print("Orginal Matrix is:\n",matrix)

B = matrix.copy()
B[0, 0] = B[0, 0]+ 1
print(B)

Orginal Matrix is:
 [[0 9]
 [9 1]]
[[1 9]
 [9 1]]


#Re-anlayze Matrix

In [17]:
shape_B = B.shape
print(shape_B)

det_B = np.linalg.det(B)
print(det_B)

rank_B = np.linalg.matrix_rank(B)
print(rank_B)

eigenvalu  = np.linalg.eigvals(B)
print(eigenvalu)

#Inverse Matrix B
if det_B != 0:
  inv_B = np.linalg.inv(B)
  print(inv_B)
else:
  print("Inverse dose't exist")

(2, 2)
-79.99999999999997
2
[10. -8.]
[[-0.0125  0.1125]
 [ 0.1125 -0.0125]]


#Question 1: How did the determinant change and why?
Answer:

 The determinant changed from -81 to around -80 (it increased by 1).

Beacuse, The determinant of a 2×2 matrix [[a,b],[c,d]] is calculated as (a×d) - (b×c). When I changed the value at position [0,0] (which is 'a') from 0 to 1:

The calculation changed from (0×1) - (9×9) = -81 to (1×1) - (9×9) = -80


#Question 2: Did the rank change? Explain.
Answer: No, the rank did not change. Both matrices have rank = 2.

Beacuse, Rank is the number of linearly independent rows or columns in a matrix. A 2×2 matrix has full rank (rank = 2) when its determinant is non-zero. Since both Matrix A (det = -81) and Matrix B (det = -80) have non-zero determinants, both have full rank = 2.

#Question 3: How did the eigenvalues respond to the value change?
Answer:
 Both eigenvalues increased.

Matrix A eigenvalues: 9.91 and -8.91

Matrix B eigenvalues: 10.00 and -8.00

 Eigenvalues depend on the trace (sum of diagonal elements) and determinant of the matrix. When I changed [0,0] from 0 to 1:

The trace increased from 0+1=1 to 1+1=2

The determinant increased from -81 to -80

These changes caused both eigenvalues to shift upward in value

#Question 4: Is B easier or harder to invert than A? Why?
Answer:
 Matrix B is very slightly easier to invert than Matrix A.
Because
Larger determinant magnitude: B has determinant -80 compared to A's -81. A larger

Well-conditioned: Both matrices have eigenvalues that are not close to zero

Similar inverse values: The inverse elements of both matrices are similar in magnitude, so there's no significant difference in computational difficulty.